/*
  COMPLETE WORD DATA — extracted from:
  "The Top 500 Words" by Yaqeen Books / Quran Memorization Guide
  © Yaqeen Books 2022 — www.yaqeenbooks.com

  SECTION 1: Most Common Nouns/Particles (#1-#336)
  SECTION 2: Common Verbs (#1-#234)

  STATUS:
  - Word numbers and English meanings: EXTRACTED from PDF
  - Arabic script and ayah examples: Need to be filled in
  - Occurrences in Quran: EXTRACTED from PDF where available

  FORMAT FOR EACH WORD:
  {
    section: 1 or 2,
    wordNumber: "#1",
    arabic: "",           // ADD Arabic script
    transliteration: "",  // from PDF
    english: "",          // from PDF
    occurrences: 0,       // from PDF
    ayah_ar: "",          // ADD example ayah
    ayah_en: "",          // ADD translation
    ref: ""               // ADD reference
  }
*/

// ============================================================
// SECTION 1 — MOST COMMON NOUNS & PARTICLES (#1–#336)
// ============================================================
const SECTION_1_WORDS = [
  // --- DEMONSTRATIVES ---
  { section:1, wordNumber:"#1", arabic:"هَذَا", transliteration:"Hadha", english:"This (masculine)", occurrences:182 },
  { section:1, wordNumber:"#2", arabic:"ذَٰلِكَ", transliteration:"Dhalika", english:"That", occurrences:461 },
  { section:1, wordNumber:"#3", arabic:"هَٰذِهِ", transliteration:"Hadhihi", english:"This (feminine)", occurrences:46 },
  { section:1, wordNumber:"#4", arabic:"تِلْكَ", transliteration:"Tilka", english:"That (feminine)", occurrences:28 },
  { section:1, wordNumber:"#5", arabic:"هَٰؤُلَاءِ", transliteration:"Haulai", english:"These", occurrences:40 },
  { section:1, wordNumber:"#6", arabic:"أُولَٰئِكَ", transliteration:"Ulaika", english:"Those", occurrences:130 },
  { section:1, wordNumber:"#7", arabic:"الَّذِي", transliteration:"Alladhi", english:"He who / That which", occurrences:258 },
  { section:1, wordNumber:"#8", arabic:"الَّتِي", transliteration:"Allati", english:"She who / That which (fem)", occurrences:56 },
  { section:1, wordNumber:"#9", arabic:"الَّذِينَ", transliteration:"Alladhina", english:"Those who", occurrences:738 },
  { section:1, wordNumber:"#10", arabic:"هَٰذِهِ", transliteration:"Hadhihi", english:"These", occurrences:45 },
  { section:1, wordNumber:"#11", arabic:"تِلْكَ", transliteration:"Tilka", english:"Those (fem)", occurrences:28 },
  { section:1, wordNumber:"#12", arabic:"الَّتِي", transliteration:"Allati", english:"That (fem relative)", occurrences:56 },

  // --- NEGATIONS ---
  { section:1, wordNumber:"#13", arabic:"لَا إِلَٰهَ", transliteration:"La ilaha", english:"There is no God", occurrences:36 },
  { section:1, wordNumber:"#14", arabic:"إِلَّا اللَّهُ", transliteration:"Illa-Allah", english:"Except Allah", occurrences:19 },
  { section:1, wordNumber:"#15", arabic:"كَلَّا", transliteration:"Kalla", english:"No! / Certainly not!", occurrences:38 },
  { section:1, wordNumber:"#16", arabic:"لَنْ", transliteration:"Lan", english:"Will not (future negation)", occurrences:59 },
  { section:1, wordNumber:"#17", arabic:"لَمْ", transliteration:"Lam", english:"Did not (past negation)", occurrences:172 },
  { section:1, wordNumber:"#18", arabic:"مَا", transliteration:"Ma", english:"Not / What / That which", occurrences:890 },
  { section:1, wordNumber:"#19", arabic:"لَيْسَ", transliteration:"Laysa", english:"Is not / There is not", occurrences:45 },
  { section:1, wordNumber:"#20", arabic:"بَلَىٰ", transliteration:"Bala", english:"Yes / Indeed (affirmative)", occurrences:22 },
  { section:1, wordNumber:"#21", arabic:"غَيْرُ", transliteration:"Ghayr", english:"Other than / Not", occurrences:69 },
  { section:1, wordNumber:"#22", arabic:"دُونَ", transliteration:"Duna", english:"Besides / Other than / Less than", occurrences:90 },
  { section:1, wordNumber:"#23", arabic:"إِلَّا", transliteration:"Illa", english:"Except / Only", occurrences:680 },
  { section:1, wordNumber:"#24", arabic:"نَعَمْ", transliteration:"Na'am", english:"Yes", occurrences:9 },

  // --- PRONOUNS ---
  { section:1, wordNumber:"#25", arabic:"هُ / هِ", transliteration:"Hu / Hi", english:"His / Him (suffix)", occurrences:4906 },
  { section:1, wordNumber:"#26", arabic:"هُمْ", transliteration:"Hum", english:"They (masc. plural)", occurrences:257 },
  { section:1, wordNumber:"#27", arabic:"كُمْ", transliteration:"Kum", english:"Your / You (plural suffix)", occurrences:12 },
  { section:1, wordNumber:"#28", arabic:"نِي / ي", transliteration:"Ni / I", english:"My / Me (suffix)", occurrences:24 },
  { section:1, wordNumber:"#29", arabic:"نَا", transliteration:"Na", english:"Our / Us (suffix)", occurrences:2145 },
  { section:1, wordNumber:"#30", arabic:"هَا", transliteration:"Ha", english:"Its / Her (suffix)", occurrences:4 },
  { section:1, wordNumber:"#31", arabic:"هُنَّ", transliteration:"Hunna", english:"They (fem. plural)", occurrences:6 },
  { section:1, wordNumber:"#32", arabic:"كِ", transliteration:"Ki", english:"Your / You (fem. singular suffix)", occurrences:0 },
  { section:1, wordNumber:"#33", arabic:"هَا", transliteration:"Ha", english:"Her (object suffix)", occurrences:4 },
  { section:1, wordNumber:"#34", arabic:"هُمَا", transliteration:"Huma", english:"They (dual)", occurrences:116 },
  { section:1, wordNumber:"#35", arabic:"كُمَا", transliteration:"Kuma", english:"Your (dual)", occurrences:58 },
  { section:1, wordNumber:"#36", arabic:"هُوَ", transliteration:"Huwa", english:"He", occurrences:244 },
  { section:1, wordNumber:"#37", arabic:"أَنتَ", transliteration:"Anta", english:"You (masc. singular)", occurrences:55 },
  { section:1, wordNumber:"#38", arabic:"أَنتُمْ", transliteration:"Antum", english:"You all (plural)", occurrences:78 },
  { section:1, wordNumber:"#39", arabic:"أَنَا", transliteration:"Ana", english:"I", occurrences:430 },
  { section:1, wordNumber:"#40", arabic:"نَحْنُ", transliteration:"Nahnu", english:"We", occurrences:62 },
  { section:1, wordNumber:"#41", arabic:"هِيَ", transliteration:"Hiya", english:"She / It", occurrences:47 },
  { section:1, wordNumber:"#42", arabic:"هُنَّ", transliteration:"Hunna", english:"They (fem.)", occurrences:6 },
  { section:1, wordNumber:"#44", arabic:"هِيَ", transliteration:"Hiya", english:"It is / They are (dual)", occurrences:47 },
  { section:1, wordNumber:"#45", arabic:"هُمَا", transliteration:"Huma", english:"Those (two)", occurrences:1 },
  { section:1, wordNumber:"#46", arabic:"أَنتُمَا", transliteration:"Antuma", english:"You (two)", occurrences:1 },

  // --- PREPOSITIONS / LOCATIONS ---
  { section:1, wordNumber:"#47", arabic:"فَوْقَ", transliteration:"Fawqa", english:"Above / Over", occurrences:15 },
  { section:1, wordNumber:"#48", arabic:"تَحْتَ", transliteration:"Tahta", english:"Under / Below", occurrences:7 },
  { section:1, wordNumber:"#49", arabic:"بَيْنَ يَدَيْ", transliteration:"Bayna Yaday", english:"In front of", occurrences:9 },
  { section:1, wordNumber:"#50", arabic:"خَلْفَ", transliteration:"Khalfa", english:"Behind / After", occurrences:2 },
  { section:1, wordNumber:"#51", arabic:"أَمَامَ", transliteration:"Amama", english:"In front of", occurrences:1 },
  { section:1, wordNumber:"#52", arabic:"وَرَاءَ", transliteration:"Wara", english:"Behind / Beyond", occurrences:12 },
  { section:1, wordNumber:"#53", arabic:"يَمِين", transliteration:"Yameen", english:"Right / Oath", occurrences:3 },
  { section:1, wordNumber:"#54", arabic:"شِمَال", transliteration:"Shimal", english:"Left", occurrences:7 },
  { section:1, wordNumber:"#55", arabic:"بَيْنَ", transliteration:"Bayna", english:"Between / Among", occurrences:76 },
  { section:1, wordNumber:"#56", arabic:"حَوْلَ", transliteration:"Hawla", english:"Around", occurrences:2 },
  { section:1, wordNumber:"#57", arabic:"حَيْثُ", transliteration:"Haythu", english:"Wherever / Where", occurrences:28 },
  { section:1, wordNumber:"#58", arabic:"أَيْنَمَا", transliteration:"Aynama", english:"Wherever", occurrences:3 },

  // --- QUESTION WORDS ---
  { section:1, wordNumber:"#59", arabic:"مَاذَا", transliteration:"Madha", english:"What?", occurrences:22 },
  { section:1, wordNumber:"#60", arabic:"مَنْ", transliteration:"Man", english:"Who? / Whoever", occurrences:2023 },
  { section:1, wordNumber:"#61", arabic:"مَتَى", transliteration:"Mata", english:"When?", occurrences:9 },
  { section:1, wordNumber:"#62", arabic:"أَيْنَ", transliteration:"Ayna", english:"Where?", occurrences:14 },
  { section:1, wordNumber:"#63", arabic:"كَيْفَ", transliteration:"Kayfa", english:"How?", occurrences:62 },
  { section:1, wordNumber:"#64", arabic:"كَمْ", transliteration:"Kam", english:"How many?", occurrences:12 },
  { section:1, wordNumber:"#65", arabic:"أَيُّ", transliteration:"Ayyu", english:"Which? / Whichever", occurrences:7 },
  { section:1, wordNumber:"#66", arabic:"أَنَّى", transliteration:"Anna", english:"Where from? / Why?", occurrences:15 },
  { section:1, wordNumber:"#67", arabic:"أَ / هَلْ", transliteration:"A / Hal", english:"Is? / Am? / Are? / Do?", occurrences:64 },
  { section:1, wordNumber:"#68", arabic:"مَاذَا", transliteration:"Madha", english:"What (question)", occurrences:22 },
  { section:1, wordNumber:"#69", arabic:"لِمَ / لِمَاذَا", transliteration:"Lima / Limatha", english:"Why?", occurrences:172 },

  // --- CONDITIONALS ---
  { section:1, wordNumber:"#70", arabic:"لَوْلَا", transliteration:"Lawla", english:"If not / Why not?", occurrences:38 },
  { section:1, wordNumber:"#71", arabic:"ذُو / ذَا / ذِي", transliteration:"Dhu / Dha / Dhi", english:"Have / Owner of / Possessor of", occurrences:25 },
  { section:1, wordNumber:"#72", arabic:"ذَات", transliteration:"Dhata", english:"Endowed with / Owner (fem.)", occurrences:16 },
  { section:1, wordNumber:"#73", arabic:"أُولُو / أُولِي", transliteration:"Ulu / Uli", english:"People of / Owners of", occurrences:38 },
  { section:1, wordNumber:"#74", arabic:"أَهْل", transliteration:"Ahl", english:"People of / Relatives", occurrences:56 },
  { section:1, wordNumber:"#75", arabic:"آل", transliteration:"Al", english:"Family / Relatives / People", occurrences:22 },
  { section:1, wordNumber:"#76", arabic:"أَلَا", transliteration:"Ala", english:"Do not / Will not (warning)", occurrences:680 },
  { section:1, wordNumber:"#77", arabic:"نِعْمَ", transliteration:"Ni'ma", english:"What an excellent / How good!", occurrences:9 },
  { section:1, wordNumber:"#78", arabic:"بِئْسَ", transliteration:"Bi'sa", english:"What an evil / How bad!", occurrences:5 },
  { section:1, wordNumber:"#79", arabic:"بِئْسَمَا", transliteration:"Bi'sama", english:"Evil is that which", occurrences:3 },
  { section:1, wordNumber:"#80", arabic:"مِثْلُ", transliteration:"Mithlu", english:"The same / Similar", occurrences:46 },
  { section:1, wordNumber:"#81", arabic:"مَثَل", transliteration:"Mathal", english:"Lesson / Example / Parable", occurrences:46 },
  { section:1, wordNumber:"#82", arabic:"مِمَّنْ", transliteration:"Mimman", english:"Than the one who / From those who", occurrences:31 },

  // --- TIME WORDS ---
  { section:1, wordNumber:"#83", arabic:"قَبْلَ", transliteration:"Qabla", english:"Before", occurrences:118 },
  { section:1, wordNumber:"#84", arabic:"بَعْدَ", transliteration:"Ba'da", english:"After", occurrences:114 },
  { section:1, wordNumber:"#85", arabic:"حِينَ", transliteration:"Hina", english:"Time period / At the time of", occurrences:15 },
  { section:1, wordNumber:"#86", arabic:"إِذْ", transliteration:"Idh", english:"When (past event)", occurrences:156 },
  { section:1, wordNumber:"#87", arabic:"إِذَا", transliteration:"Idha", english:"When / If (future)", occurrences:210 },
  { section:1, wordNumber:"#88", arabic:"ثُمَّ", transliteration:"Thumma", english:"Then / After that", occurrences:300 },
  { section:1, wordNumber:"#89", arabic:"فَ", transliteration:"Fa", english:"Then / Thus / Therefore", occurrences:999 },
  { section:1, wordNumber:"#90", arabic:"بَلْ", transliteration:"Bal", english:"Rather / But / However", occurrences:121 },
  { section:1, wordNumber:"#91", arabic:"عِنْدَ / لَدَى / لَدُنْ", transliteration:"Inda/Ladai/Laddun", english:"Near / With / At", occurrences:144 },
  { section:1, wordNumber:"#92", arabic:"إِنْ...إِلَّا", transliteration:"In...illa", english:"Nothing but", occurrences:1351 },
  { section:1, wordNumber:"#93", arabic:"مَا...إِلَّا", transliteration:"Ma...illa", english:"Nothing but", occurrences:890 },
  { section:1, wordNumber:"#94", arabic:"إِنْ...إِلَّا", transliteration:"An...illa", english:"Nothing except", occurrences:0 },

  // --- PREPOSITIONS ---
  { section:1, wordNumber:"#95", arabic:"بِ", transliteration:"Bi", english:"With / In / From (preposition)", occurrences:0 },
  { section:1, wordNumber:"#96", arabic:"عَمَّا", transliteration:"Amma", english:"About what / Concerning", occurrences:0 },
  { section:1, wordNumber:"#97", arabic:"مِمَّا", transliteration:"Mimma", english:"From what / Of what", occurrences:0 },
  { section:1, wordNumber:"#98", arabic:"كَمَا", transliteration:"Kama", english:"As / Just as", occurrences:0 },
  { section:1, wordNumber:"#99", arabic:"لِمَا", transliteration:"Lima", english:"For what / That which", occurrences:0 },
  { section:1, wordNumber:"#100", arabic:"مِمَّا", transliteration:"Mimma", english:"Out of what", occurrences:46 },
  { section:1, wordNumber:"#101", arabic:"لَكَ", transliteration:"Laka", english:"For you / Yours", occurrences:0 },
  { section:1, wordNumber:"#102", arabic:"لَكُمْ", transliteration:"Lakum", english:"For you all / Yours (plural)", occurrences:0 },
  { section:1, wordNumber:"#103", arabic:"أَمَّا", transliteration:"Amma", english:"As for / As to", occurrences:17 },
  { section:1, wordNumber:"#104", arabic:"إِمَّا", transliteration:"Imma", english:"Either / Or", occurrences:17 },
  { section:1, wordNumber:"#105", arabic:"أَنَّمَا", transliteration:"Annama", english:"That / Verily", occurrences:125 },
  { section:1, wordNumber:"#106", arabic:"إِنَّمَا", transliteration:"Innama", english:"Verily / Is but / Only", occurrences:125 },
  { section:1, wordNumber:"#107", arabic:"كَأَنَّمَا", transliteration:"Ka-annama", english:"As if", occurrences:3 },
  { section:1, wordNumber:"#108", arabic:"كُلَّمَا", transliteration:"Kullama", english:"Whenever / Every time", occurrences:12 },
  { section:1, wordNumber:"#109", arabic:"بِ", transliteration:"Bi", english:"With / In / From", occurrences:0 },
  { section:1, wordNumber:"#110", arabic:"مِنْ", transliteration:"Min", english:"From / Of / Among", occurrences:0 },
  { section:1, wordNumber:"#111", arabic:"فِي", transliteration:"Fi", english:"In / Into / Among", occurrences:0 },
  { section:1, wordNumber:"#112", arabic:"كَ", transliteration:"Ka", english:"As / Like", occurrences:0 },
  { section:1, wordNumber:"#113", arabic:"لِ", transliteration:"Li", english:"For / To (purpose)", occurrences:0 },
  { section:1, wordNumber:"#114", arabic:"عَنْ", transliteration:"An", english:"About / From / Away from", occurrences:0 },
  { section:1, wordNumber:"#115", arabic:"عَلَى", transliteration:"Ala", english:"On / Upon / Over", occurrences:0 },
  { section:1, wordNumber:"#116", arabic:"تَ", transliteration:"Ta", english:"By (oath)", occurrences:0 },
  { section:1, wordNumber:"#117", arabic:"حَتَّى", transliteration:"Hatta", english:"Until / So that / Even", occurrences:0 },
  { section:1, wordNumber:"#118", arabic:"إِلَى", transliteration:"Ila", english:"To / Towards / Until", occurrences:0 },
  { section:1, wordNumber:"#119", arabic:"مَعَ", transliteration:"Ma'a", english:"With / Together with", occurrences:0 },
  { section:1, wordNumber:"#120", arabic:"وَ", transliteration:"Wa", english:"And / While / By (oath)", occurrences:0 },
  { section:1, wordNumber:"#121", arabic:"قَدْ", transliteration:"Qad", english:"Already / Indeed / May", occurrences:0 },
  { section:1, wordNumber:"#122", arabic:"سَ", transliteration:"Sa", english:"Will (future prefix)", occurrences:0 },
  { section:1, wordNumber:"#123", arabic:"سَوْفَ", transliteration:"Sawfa", english:"Will (future)", occurrences:7 },
  { section:1, wordNumber:"#124", arabic:"لَ + verb + نَّ", transliteration:"La...anna", english:"Surely will (emphasis + future)", occurrences:0 },
  { section:1, wordNumber:"#125", arabic:"لَ", transliteration:"La", english:"Surely / Indeed (emphasis)", occurrences:0 },
  { section:1, wordNumber:"#126", arabic:"لَ", transliteration:"La", english:"Indeed / Surely", occurrences:0 },
  { section:1, wordNumber:"#127", arabic:"أَلْ", transliteration:"Al", english:"The (definite article)", occurrences:0 },
  { section:1, wordNumber:"#128", arabic:"أَلْ", transliteration:"Al", english:"The (definite article)", occurrences:0 },
  { section:1, wordNumber:"#129", arabic:"لَمَّا", transliteration:"Lamma", english:"When / Not yet", occurrences:0 },
  { section:1, wordNumber:"#130", arabic:"لَوْ", transliteration:"Law", english:"If (hypothetical)", occurrences:0 },
  { section:1, wordNumber:"#131", arabic:"بَعْضُ", transliteration:"Ba'd", english:"Some / Part of", occurrences:0 },
  { section:1, wordNumber:"#132", arabic:"كُلَّ", transliteration:"Kulla", english:"Every / All", occurrences:54 },
  { section:1, wordNumber:"#133", arabic:"إِنَّ", transliteration:"Inna", english:"Verily / Truly / Indeed", occurrences:1351 },
  { section:1, wordNumber:"#134", arabic:"أَنَّ", transliteration:"Anna", english:"That (conjunction)", occurrences:0 },
  { section:1, wordNumber:"#135", arabic:"كَأَنَّ", transliteration:"Ka-anna", english:"As if", occurrences:306 },
  { section:1, wordNumber:"#136", arabic:"لَٰكِنَّ", transliteration:"Lakinna", english:"But / However", occurrences:171 },
  { section:1, wordNumber:"#137", arabic:"لَعَلَّ", transliteration:"La'alla", english:"Maybe / Perhaps", occurrences:3 },
  { section:1, wordNumber:"#138", arabic:"أَنْ", transliteration:"An", english:"That / To (infinitive)", occurrences:0 },
  { section:1, wordNumber:"#139", arabic:"لَنْ", transliteration:"Lan", english:"Never / Will not", occurrences:0 },
  { section:1, wordNumber:"#140", arabic:"إِنْ", transliteration:"In", english:"If / Verily (conditional)", occurrences:0 },
  { section:1, wordNumber:"#141", arabic:"أَوْ", transliteration:"Aw", english:"Or / Either", occurrences:0 },
  { section:1, wordNumber:"#142", arabic:"لَمَّا", transliteration:"Lamma", english:"When (past)", occurrences:54 },
  { section:1, wordNumber:"#143", arabic:"لَوْ", transliteration:"Law", english:"If (hypothetical past)", occurrences:0 },
  { section:1, wordNumber:"#144", arabic:"أَمَّا", transliteration:"Amma", english:"As for", occurrences:0 },

  // --- DIVINE NAMES & ATTRIBUTES ---
  { section:1, wordNumber:"#145", arabic:"رَبّ", transliteration:"Rabb", english:"Lord / Sustainer", occurrences:0 },
  { section:1, wordNumber:"#146", arabic:"رَبِّ", transliteration:"Rabbi", english:"My Lord", occurrences:0 },
  { section:1, wordNumber:"#147", arabic:"رَحْمَٰن", transliteration:"Rahman", english:"The Most Gracious", occurrences:64 },
  { section:1, wordNumber:"#148", arabic:"رَحِيم", transliteration:"Rahim", english:"The Most Merciful", occurrences:0 },
  { section:1, wordNumber:"#149", arabic:"سَمِيع", transliteration:"Sami", english:"All-Hearing", occurrences:47 },
  { section:1, wordNumber:"#150", arabic:"بَصِير", transliteration:"Basir", english:"All-Seeing", occurrences:0 },
  { section:1, wordNumber:"#151", arabic:"عَزِيز", transliteration:"Aziz", english:"Mighty / Exalted in Might", occurrences:0 },
  { section:1, wordNumber:"#152", arabic:"غَفُور", transliteration:"Ghafur", english:"Oft-Forgiving", occurrences:91 },
  { section:1, wordNumber:"#153", arabic:"قَادِر", transliteration:"Qadir", english:"All-Powerful", occurrences:50 },
  { section:1, wordNumber:"#154", arabic:"خَبِير", transliteration:"Khabir", english:"All-Aware", occurrences:0 },
  { section:1, wordNumber:"#155", arabic:"قَدِير", transliteration:"Qadir", english:"Omnipotent", occurrences:0 },
  { section:1, wordNumber:"#156", arabic:"وَكِيل", transliteration:"Wakil", english:"Trustee / Guardian", occurrences:0 },
  { section:1, wordNumber:"#157", arabic:"وَلِيّ", transliteration:"Waliyy", english:"Protecting friend / Guardian", occurrences:0 },
  { section:1, wordNumber:"#158", arabic:"حَكِيم", transliteration:"Hakim", english:"All-Wise", occurrences:0 },
  { section:1, wordNumber:"#159", arabic:"غَفَّار", transliteration:"Ghaffar", english:"The Repeatedly Forgiving", occurrences:0 },
  { section:1, wordNumber:"#160", arabic:"أَمِين", transliteration:"Amin", english:"Trustworthy / Faithful", occurrences:0 },
  { section:1, wordNumber:"#161", arabic:"رَزَّاق", transliteration:"Razzaq", english:"The Provider", occurrences:0 },
  { section:1, wordNumber:"#162", arabic:"شَهِيد", transliteration:"Shahid", english:"Witness", occurrences:0 },
  { section:1, wordNumber:"#163", arabic:"تَوَّاب", transliteration:"Tawwab", english:"The Accepter of Repentance", occurrences:0 },
  { section:1, wordNumber:"#164", arabic:"حَفِيظ", transliteration:"Hafiz", english:"Preserver / Guardian", occurrences:0 },
  { section:1, wordNumber:"#165", arabic:"مُؤْمِن", transliteration:"Mumin", english:"Believer / Granter of Security", occurrences:0 },
  { section:1, wordNumber:"#166", arabic:"مُهَيْمِن", transliteration:"Muhaymin", english:"The Dominant / Guardian", occurrences:0 },
  { section:1, wordNumber:"#167", arabic:"حَمِيد", transliteration:"Hamid", english:"The Praiseworthy", occurrences:0 },
  { section:1, wordNumber:"#168", arabic:"حَمِيم", transliteration:"Hamim", english:"Close friend / Warm", occurrences:0 },

  // --- COMPARATIVES ---
  { section:1, wordNumber:"#169", arabic:"أَشَدّ", transliteration:"Ashad", english:"Most severe / Strongest", occurrences:0 },
  { section:1, wordNumber:"#170", arabic:"أَعْلَى", transliteration:"A'la", english:"Higher / Superior", occurrences:9 },
  { section:1, wordNumber:"#171", arabic:"أَعْلَم", transliteration:"A'lam", english:"Most knowing", occurrences:0 },
  { section:1, wordNumber:"#172", arabic:"أَكْبَر", transliteration:"Akbar", english:"Greater / Biggest", occurrences:0 },
  { section:1, wordNumber:"#173", arabic:"أَكْبَر", transliteration:"Akbar", english:"Greatest", occurrences:0 },
  { section:1, wordNumber:"#174", arabic:"أَكْثَر", transliteration:"Akthar", english:"More / Most", occurrences:80 },
  { section:1, wordNumber:"#175", arabic:"أَحْسَن", transliteration:"Ahsan", english:"Best / Most beautiful", occurrences:0 },
  { section:1, wordNumber:"#176", arabic:"أَحَقّ", transliteration:"Ahaq", english:"More worthy / Most deserving", occurrences:0 },
  { section:1, wordNumber:"#177", arabic:"أَدْنَى", transliteration:"Adna", english:"Nearer / Lower / Less", occurrences:0 },
  { section:1, wordNumber:"#178", arabic:"أَظْلَم", transliteration:"Azlam", english:"More unjust", occurrences:17 },
  { section:1, wordNumber:"#179", arabic:"أَهْدَى", transliteration:"Ahda", english:"Better guided", occurrences:6 },
  { section:1, wordNumber:"#180", arabic:"أَوْلَى", transliteration:"Awla", english:"More worthy / More appropriate", occurrences:0 },

  // --- ADJECTIVES ---
  { section:1, wordNumber:"#181", arabic:"شَدِيد", transliteration:"Shadid", english:"Severe / Strong / Intense", occurrences:28 },
  { section:1, wordNumber:"#182", arabic:"عَلِيّ", transliteration:"Aliy", english:"High / Exalted", occurrences:16 },
  { section:1, wordNumber:"#183", arabic:"عَظِيم", transliteration:"Azim", english:"Great / Mighty", occurrences:0 },
  { section:1, wordNumber:"#184", arabic:"قَرِيب", transliteration:"Qarib", english:"Near / Close", occurrences:0 },
  { section:1, wordNumber:"#185", arabic:"كَبِير", transliteration:"Kabir", english:"Great / Large / Old", occurrences:0 },
  { section:1, wordNumber:"#186", arabic:"كَثِير", transliteration:"Kathir", english:"Much / Many / Plenty", occurrences:71 },
  { section:1, wordNumber:"#187", arabic:"صَغِير", transliteration:"Saghir", english:"Small / Young / Little", occurrences:0 },
  { section:1, wordNumber:"#188", arabic:"حَكِيم", transliteration:"Hakim", english:"Wise / All-Wise", occurrences:0 },
  { section:1, wordNumber:"#189", arabic:"عَلِيم", transliteration:"Alim", english:"All-Knowing", occurrences:0 },
  { section:1, wordNumber:"#190", arabic:"جَمِيل", transliteration:"Jamil", english:"Beautiful / Gracious", occurrences:0 },
  { section:1, wordNumber:"#191", arabic:"كَرِيم", transliteration:"Karim", english:"Noble / Honourable / Generous", occurrences:0 },
  { section:1, wordNumber:"#192", arabic:"لَطِيف", transliteration:"Latif", english:"Subtle / Kind / Gentle", occurrences:0 },
  { section:1, wordNumber:"#193", arabic:"رَسُول", transliteration:"Rasul", english:"Messenger", occurrences:0 },
  { section:1, wordNumber:"#194", arabic:"نَبِيّ", transliteration:"Nabiy", english:"Prophet", occurrences:0 },
  { section:1, wordNumber:"#195", arabic:"أَنْبِيَاء", transliteration:"Anbiya", english:"Prophets (plural)", occurrences:0 },
  { section:1, wordNumber:"#196", arabic:"آدَم / نُوح / إِبْرَاهِيم", transliteration:"Adam/Nooh/Ibrahim", english:"Adam, Noah, Abraham (Prophets)", occurrences:0 },

  // --- ISLAMIC CONCEPTS ---
  { section:1, wordNumber:"#201", arabic:"شَيْطَان", transliteration:"Shaytan", english:"Satan / Devil", occurrences:63 },
  { section:1, wordNumber:"#205", arabic:"آيَة", transliteration:"Ayah", english:"Verse / Sign", occurrences:0 },
  { section:1, wordNumber:"#206", arabic:"بَيِّنَات", transliteration:"Bayyinat", english:"Clear evidence / Proofs", occurrences:20 },
  { section:1, wordNumber:"#207", arabic:"قُرْآن", transliteration:"Quran", english:"The Quran", occurrences:0 },
  { section:1, wordNumber:"#221", arabic:"قِيَامَة", transliteration:"Qiyamat", english:"Resurrection / Day of Judgement", occurrences:70 },
  { section:1, wordNumber:"#228", arabic:"يَوْمَئِذٍ", transliteration:"Yawma'idhin", english:"That Day", occurrences:69 },
  { section:1, wordNumber:"#229", arabic:"أَبَدًا", transliteration:"Abadan", english:"Forever / Ever / Never", occurrences:0 },
  { section:1, wordNumber:"#231", arabic:"الْآخِرَة", transliteration:"Al Akhira", english:"The Hereafter / The After", occurrences:110 },
  { section:1, wordNumber:"#233", arabic:"ثَوَاب", transliteration:"Thawab", english:"Reward", occurrences:9 },
  { section:1, wordNumber:"#237", arabic:"جَهَنَّم", transliteration:"Jahannam", english:"Hell / Hellfire", occurrences:77 },
  { section:1, wordNumber:"#240", arabic:"أَمْر", transliteration:"Amr", english:"Matter / Affair / Command", occurrences:13 },
  { section:1, wordNumber:"#244", arabic:"حِكْمَة", transliteration:"Hik'mat", english:"Wisdom", occurrences:20 },
  { section:1, wordNumber:"#246", arabic:"دِين", transliteration:"Din", english:"Religion / Way of life / Judgement", occurrences:0 },
  { section:1, wordNumber:"#247", arabic:"زَكَاة", transliteration:"Zakat", english:"Charity / Purification / Poor-due", occurrences:32 },
  { section:1, wordNumber:"#251", arabic:"أَجَل", transliteration:"Ajal", english:"Fixed time / Term / Death", occurrences:0 },
  { section:1, wordNumber:"#253", arabic:"أَحَد", transliteration:"Ahad", english:"One / Unique / Anyone", occurrences:0 },
  { section:1, wordNumber:"#256", arabic:"شَهَادَة", transliteration:"Shahadat", english:"Witness / Testimony", occurrences:19 },
  { section:1, wordNumber:"#262", arabic:"مَلَائِكَة", transliteration:"Malaika", english:"Angels", occurrences:0 },
  { section:1, wordNumber:"#264", arabic:"وَاحِد", transliteration:"Wahid", english:"One", occurrences:60 },

  // --- GOOD & EVIL ---
  { section:1, wordNumber:"#266", arabic:"حَسَنَات", transliteration:"Hasanat", english:"Good deeds", occurrences:27 },
  { section:1, wordNumber:"#267", arabic:"سَيِّئَات", transliteration:"Sayyiat", english:"Evil deeds / Bad", occurrences:21 },
  { section:1, wordNumber:"#268", arabic:"خَيْر", transliteration:"Khair", english:"Good / Better / Best", occurrences:174 },
  { section:1, wordNumber:"#269", arabic:"شَرّ", transliteration:"Sharr", english:"Evil / Bad / Worse", occurrences:15 },
  { section:1, wordNumber:"#270", arabic:"إِثْم", transliteration:"Ithm", english:"Sin", occurrences:40 },
  { section:1, wordNumber:"#272", arabic:"جُنَاح", transliteration:"Junah", english:"Sin / Blame", occurrences:30 },
  { section:1, wordNumber:"#273", arabic:"حَرَام", transliteration:"Haram", english:"Unlawful / Forbidden", occurrences:21 },
  { section:1, wordNumber:"#275", arabic:"حَدِيث", transliteration:"Hadith", english:"Speech / Story / Narration", occurrences:23 },
  { section:1, wordNumber:"#278", arabic:"فَضْل", transliteration:"Fadl", english:"Grace / Bounty / Favour", occurrences:94 },
  { section:1, wordNumber:"#280", arabic:"مُلْك", transliteration:"Mulk", english:"Kingdom / Dominion / Reign", occurrences:31 },
  { section:1, wordNumber:"#281", arabic:"نِعْمَة", transliteration:"Ni'mat", english:"Favour / Blessing", occurrences:25 },
  { section:1, wordNumber:"#283", arabic:"إِذْن", transliteration:"Idhn", english:"Permission / Leave", occurrences:71 },
  { section:1, wordNumber:"#285", arabic:"جَمِيع", transliteration:"Jami'", english:"All / Everybody / Together", occurrences:50 },
  { section:1, wordNumber:"#287", arabic:"فَرِيق", transliteration:"Fareeq", english:"Party / Group", occurrences:29 },
  { section:1, wordNumber:"#288", arabic:"أُمَّة", transliteration:"Umma", english:"Nation / Community", occurrences:119 },

  // --- FAMILY & PEOPLE ---
  { section:1, wordNumber:"#289", arabic:"أَبّ / أَبَت", transliteration:"Abb/Abat", english:"Father", occurrences:21 },
  { section:1, wordNumber:"#290", arabic:"زَوْج", transliteration:"Zawj", english:"Spouse / Pair / Partner", occurrences:27 },
  { section:1, wordNumber:"#292", arabic:"رَجُل", transliteration:"Rajul", english:"Man", occurrences:41 },
  { section:1, wordNumber:"#293", arabic:"امْرَأَة", transliteration:"Imra-at", english:"Woman", occurrences:4 },
  { section:1, wordNumber:"#294", arabic:"وَلَد", transliteration:"Walad", english:"Child / Son", occurrences:56 },
  { section:1, wordNumber:"#297", arabic:"ابْن", transliteration:"Ibn", english:"Son", occurrences:27 },
  { section:1, wordNumber:"#299", arabic:"أَخ", transliteration:"Akh", english:"Brother", occurrences:67 },
  { section:1, wordNumber:"#300", arabic:"إِخْوَان", transliteration:"Ikhwan", english:"Brothers", occurrences:20 },

  // --- BODY ---
  { section:1, wordNumber:"#301", arabic:"وَجْه", transliteration:"Wajh", english:"Face", occurrences:51 },
  { section:1, wordNumber:"#302", arabic:"عَيْن", transliteration:"Ayn", english:"Eye / Spring", occurrences:6 },
  { section:1, wordNumber:"#305", arabic:"لِسَان", transliteration:"Lisan", english:"Tongue / Language", occurrences:14 },
  { section:1, wordNumber:"#306", arabic:"قَلْب", transliteration:"Qalb", english:"Heart", occurrences:53 },
  { section:1, wordNumber:"#308", arabic:"يَد", transliteration:"Yad", english:"Hand", occurrences:542 },
  { section:1, wordNumber:"#310", arabic:"نَفْس", transliteration:"Nafs", english:"Soul / Self", occurrences:43 },
  { section:1, wordNumber:"#311", arabic:"رُوح", transliteration:"Ruh", english:"Soul / Spirit", occurrences:23 },
  { section:1, wordNumber:"#312", arabic:"قُوَّة", transliteration:"Qowwat", english:"Strength / Power", occurrences:26 },

  // --- PLACES ---
  { section:1, wordNumber:"#313", arabic:"بَيْت", transliteration:"Bayt", english:"House / Home", occurrences:32 },
  { section:1, wordNumber:"#314", arabic:"دَار", transliteration:"Dar", english:"Abode / House / Home", occurrences:41 },
  { section:1, wordNumber:"#315", arabic:"دُنْيَا", transliteration:"Dunya", english:"World / This life", occurrences:111 },
  { section:1, wordNumber:"#316", arabic:"سَبِيل", transliteration:"Sabil", english:"Way / Path / Sake (of Allah)", occurrences:156 },
  { section:1, wordNumber:"#317", arabic:"صِرَاط", transliteration:"Sirat", english:"Path / Way / Road", occurrences:32 },
  { section:1, wordNumber:"#319", arabic:"فِتْنَة", transliteration:"Fit'nat", english:"Trial / Temptation / Discord", occurrences:30 },
  { section:1, wordNumber:"#320", arabic:"قَرْيَة", transliteration:"Qaryah", english:"Village / Town", occurrences:33 },
  { section:1, wordNumber:"#321", arabic:"مَال", transliteration:"Mal", english:"Wealth / Money / Property", occurrences:84 },
  { section:1, wordNumber:"#323", arabic:"مَسْجِد", transliteration:"Masjid", english:"Mosque", occurrences:21 },
  { section:1, wordNumber:"#325", arabic:"أُمَّة", transliteration:"Ummat", english:"Nation / Community", occurrences:124 },
  { section:1, wordNumber:"#326", arabic:"قَوْم", transliteration:"Qawm", english:"People / Nation / Folk", occurrences:378 },
  { section:1, wordNumber:"#327", arabic:"إِنْسَان", transliteration:"Insan", english:"Human / Mankind", occurrences:64 },
  { section:1, wordNumber:"#328", arabic:"نَاس", transliteration:"Nas", english:"People / Mankind", occurrences:234 },
  { section:1, wordNumber:"#331", arabic:"عِبَاد", transliteration:"Ibad", english:"Servants / Slaves", occurrences:104 },
  { section:1, wordNumber:"#332", arabic:"عَدُوّ", transliteration:"Aduww", english:"Enemy", occurrences:94 },
  { section:1, wordNumber:"#333", arabic:"كُفَّار", transliteration:"Kuffar", english:"Disbelievers", occurrences:32 },
  { section:1, wordNumber:"#334", arabic:"مُجْرِم", transliteration:"Mujrim", english:"Criminal / Sinner", occurrences:52 },
  { section:1, wordNumber:"#336", arabic:"وَلِيّ", transliteration:"Waliyy", english:"Friend / Guardian / Protector", occurrences:0 },
];

// ============================================================
// SECTION 2 — COMMON VERBS (separate #1–#234 numbering)
// ============================================================
const SECTION_2_VERBS = [
  { section:2, wordNumber:"V#1", arabic:"فَعَلَ", transliteration:"Fa'ala", english:"To do / To act", occurrences:0 },
  { section:2, wordNumber:"V#2", arabic:"فَتَحَ", transliteration:"Fataha", english:"To open / To give victory", occurrences:0 },
  { section:2, wordNumber:"V#3", arabic:"بَعَثَ", transliteration:"Ba'atha", english:"To raise / To resurrect / To send", occurrences:0 },
  { section:2, wordNumber:"V#4", arabic:"جَعَلَ", transliteration:"Ja'ala", english:"To make / To place / To set up", occurrences:0 },
  { section:2, wordNumber:"V#5", arabic:"جَمَعَ", transliteration:"Jama'a", english:"To gather / To collect", occurrences:0 },
  { section:2, wordNumber:"V#6", arabic:"ذَهَبَ", transliteration:"Dhahaba", english:"To go", occurrences:0 },
  { section:2, wordNumber:"V#7", arabic:"رَفَعَ", transliteration:"Rafa'a", english:"To raise / To lift up", occurrences:0 },
  { section:2, wordNumber:"V#9", arabic:"عَمِلَ", transliteration:"Amila", english:"To act righteously / To work", occurrences:0 },
  { section:2, wordNumber:"V#16", arabic:"حَكَمَ", transliteration:"Hakama", english:"To judge / To rule", occurrences:80 },
  { section:2, wordNumber:"V#17", arabic:"جَاءَ", transliteration:"Ja'a", english:"To come", occurrences:0 },
  { section:2, wordNumber:"V#19", arabic:"خَلَقَ", transliteration:"Khalaqa", english:"To create", occurrences:0 },
  { section:2, wordNumber:"V#21", arabic:"ذَكَرَ", transliteration:"Dhakara", english:"To remember / To mention", occurrences:0 },
  { section:2, wordNumber:"V#23", arabic:"سَجَدَ", transliteration:"Sajada", english:"To prostrate", occurrences:0 },
  { section:2, wordNumber:"V#25", arabic:"شَكَرَ", transliteration:"Shakara", english:"To be grateful / To thank", occurrences:0 },
  { section:2, wordNumber:"V#26", arabic:"صَدَقَ", transliteration:"Sadaqa", english:"To be true / To say the truth", occurrences:0 },
  { section:2, wordNumber:"V#27", arabic:"عَبَدَ", transliteration:"Abada", english:"To worship", occurrences:0 },
  { section:2, wordNumber:"V#30", arabic:"قَعَدَ", transliteration:"Qa'ada", english:"To sit / To remain", occurrences:0 },
  { section:2, wordNumber:"V#31", arabic:"كَتَبَ", transliteration:"Kataba", english:"To write / To prescribe", occurrences:0 },
  { section:2, wordNumber:"V#32", arabic:"كَفَرَ", transliteration:"Kafara", english:"To disbelieve / To cover", occurrences:0 },
  { section:2, wordNumber:"V#36", arabic:"حَمَلَ", transliteration:"Hamala", english:"To carry / To bear", occurrences:0 },
  { section:2, wordNumber:"V#42", arabic:"قَدَرَ", transliteration:"Qadara", english:"To decree / To have power", occurrences:0 },
  { section:2, wordNumber:"V#46", arabic:"سَمِعَ", transliteration:"Sami'a", english:"To hear / To listen", occurrences:0 },
  { section:2, wordNumber:"V#49", arabic:"حَفِظَ", transliteration:"Hafitha", english:"To guard / To protect", occurrences:0 },
  { section:2, wordNumber:"V#51", arabic:"رَحِمَ", transliteration:"Rahima", english:"To have mercy / To be merciful", occurrences:0 },
  { section:2, wordNumber:"V#52", arabic:"شَهِدَ", transliteration:"Shahida", english:"To witness / To bear witness", occurrences:0 },
  { section:2, wordNumber:"V#53", arabic:"عَلِمَ", transliteration:"Alima", english:"To know", occurrences:0 },
  { section:2, wordNumber:"V#54", arabic:"عَمِلَ", transliteration:"Amila", english:"To work / To do", occurrences:0 },
  { section:2, wordNumber:"V#56", arabic:"رَأَى", transliteration:"Ra-a", english:"To see / To watch", occurrences:0 },
  { section:2, wordNumber:"V#66", arabic:"مَسَّ", transliteration:"Massa", english:"To touch", occurrences:0 },
  { section:2, wordNumber:"V#71", arabic:"وَهَبَ", transliteration:"Wahaba", english:"To give / To grant", occurrences:0 },
  { section:2, wordNumber:"V#72", arabic:"وَجَدَ", transliteration:"Wajada", english:"To find", occurrences:0 },
  { section:2, wordNumber:"V#76", arabic:"وَعَدَ", transliteration:"Wa'ada", english:"To promise", occurrences:0 },
  { section:2, wordNumber:"V#79", arabic:"تَابَ", transliteration:"Taba", english:"To repent", occurrences:0 },
  { section:2, wordNumber:"V#83", arabic:"قَامَ", transliteration:"Qama", english:"To stand up / To establish", occurrences:0 },
  { section:2, wordNumber:"V#85", arabic:"مَاتَ", transliteration:"Mata", english:"To die", occurrences:0 },
  { section:2, wordNumber:"V#86", arabic:"خَافَ", transliteration:"Khafa", english:"To be afraid / To fear", occurrences:0 },
  { section:2, wordNumber:"V#89", arabic:"زَادَ", transliteration:"Zada", english:"To increase / To add", occurrences:0 },
  { section:2, wordNumber:"V#90", arabic:"تَلَا", transliteration:"Tala", english:"To recite / To follow", occurrences:0 },
  { section:2, wordNumber:"V#91", arabic:"دَعَا", transliteration:"Da'a", english:"To call / To invite / To supplicate", occurrences:0 },
  { section:2, wordNumber:"V#96", arabic:"رَضِيَ", transliteration:"Radiya", english:"To be satisfied / To be content", occurrences:0 },
  { section:2, wordNumber:"V#99", arabic:"خَشِيَ", transliteration:"Khashiya", english:"To fear (with reverence)", occurrences:0 },
  { section:2, wordNumber:"V#100", arabic:"رَضِيَ", transliteration:"Radiya", english:"To be satisfied / To be content", occurrences:0 },
  { section:2, wordNumber:"V#104", arabic:"أَكَلَ", transliteration:"Akala", english:"To eat", occurrences:0 },
  { section:2, wordNumber:"V#105", arabic:"أَمَرَ", transliteration:"Amara", english:"To command / To order", occurrences:0 },
  { section:2, wordNumber:"V#117", arabic:"سَبَّحَ", transliteration:"Sabbaha", english:"To glorify / To praise", occurrences:0 },
  { section:2, wordNumber:"V#125", arabic:"نَزَّلَ", transliteration:"Nazzala", english:"To send down / To reveal", occurrences:0 },
  { section:2, wordNumber:"V#129", arabic:"قَاتَلَ", transliteration:"Qatala", english:"To fight", occurrences:0 },
  { section:2, wordNumber:"V#133", arabic:"هَاجَرَ", transliteration:"Hajara", english:"To migrate / To emigrate", occurrences:0 },
  { section:2, wordNumber:"V#135", arabic:"أَحْسَنَ", transliteration:"Ahsana", english:"To do good / To do excellently", occurrences:0 },
  { section:2, wordNumber:"V#141", arabic:"أَسْلَمَ", transliteration:"Aslama", english:"To submit / To become Muslim", occurrences:0 },
  { section:2, wordNumber:"V#150", arabic:"أَنْذَرَ", transliteration:"Andhara", english:"To warn", occurrences:0 },
  { section:2, wordNumber:"V#151", arabic:"أَنْزَلَ", transliteration:"Anzala", english:"To send down / To reveal", occurrences:0 },
  { section:2, wordNumber:"V#154", arabic:"أَنْفَقَ", transliteration:"Anfaqa", english:"To spend (in the way of Allah)", occurrences:0 },
  { section:2, wordNumber:"V#164", arabic:"أَرَادَ", transliteration:"Arada", english:"To intend / To wish / To want", occurrences:0 },
  { section:2, wordNumber:"V#166", arabic:"أَطَاعَ", transliteration:"Ata'a", english:"To obey", occurrences:0 },
  { section:2, wordNumber:"V#167", arabic:"أَقَامَ", transliteration:"Aqama", english:"To establish / To set upright", occurrences:0 },
  { section:2, wordNumber:"V#175", arabic:"أَوْحَى", transliteration:"Awha", english:"To reveal / To inspire", occurrences:0 },
  { section:2, wordNumber:"V#180", arabic:"تَدَبَّرَ", transliteration:"Tadabbara", english:"To think over / To reflect / To ponder", occurrences:0 },
  { section:2, wordNumber:"V#181", arabic:"تَذَكَّرَ", transliteration:"Tadhakkara", english:"To receive admonition / To remember", occurrences:0 },
  { section:2, wordNumber:"V#182", arabic:"تَوَكَّلَ", transliteration:"Tawakkala", english:"To put trust in / To rely on", occurrences:0 },
  { section:2, wordNumber:"V#183", arabic:"تَبَيَّنَ", transliteration:"Tabbayyana", english:"To become clear / To verify", occurrences:0 },
  { section:2, wordNumber:"V#190", arabic:"اتَّبَعَ", transliteration:"Ittaba'a", english:"To follow", occurrences:0 },
  { section:2, wordNumber:"V#191", arabic:"اتَّخَذَ", transliteration:"Ittakhadha", english:"To take / To adopt", occurrences:0 },
  { section:2, wordNumber:"V#192", arabic:"اتَّقَى", transliteration:"Ittaqa", english:"To fear Allah / To be pious", occurrences:0 },
  { section:2, wordNumber:"V#201", arabic:"اسْتَغْفَرَ", transliteration:"Istaghfara", english:"To seek forgiveness", occurrences:0 },
  { section:2, wordNumber:"V#206", arabic:"اسْتَقَامَ", transliteration:"Istaqama", english:"To be upright / To remain straight", occurrences:0 },
  { section:2, wordNumber:"V#225", arabic:"تَابَ إِلَى", transliteration:"Taba ila", english:"To repent to (Allah)", occurrences:272 },
];

// Export for use in the app
if (typeof module !== 'undefined') {
  module.exports = { SECTION_1_WORDS, SECTION_2_VERBS };
}
